<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="36305" started-at="2019-04-06T18:33:24Z" finished-at="2019-04-06T18:34:00Z">
    <groups>
    </groups>
    <test name="Maven_Automation" duration-ms="36305" started-at="2019-04-06T18:33:24Z" finished-at="2019-04-06T18:34:00Z">
      <class name="day10_0406.Express_Action_Item">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:day10_0406.Express_Action_Item@6b71769e]" name="openBrowser" is-config="true" duration-ms="7429" started-at="2019-04-06T18:33:24Z" finished-at="2019-04-06T18:33:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="expressCheckout()[pri:0, instance:day10_0406.Express_Action_Item@6b71769e]" name="expressCheckout" duration-ms="27501" started-at="2019-04-06T18:33:31Z" finished-at="2019-04-06T18:33:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Men's and Women's Clothing - Shop jeans, dresses, and suits] but found [Mens & Women's Clothing],
expected [null] but found [assertion]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Men's and Women's Clothing - Shop jeans, dresses, and suits] but found [Mens & Women's Clothing],
expected [null] but found [assertion]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at day10_0406.Express_Action_Item.expressCheckout(Express_Action_Item.java:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- expressCheckout -->
        <test-method status="PASS" signature="closeSession()[pri:0, instance:day10_0406.Express_Action_Item@6b71769e]" name="closeSession" is-config="true" duration-ms="1329" started-at="2019-04-06T18:33:59Z" finished-at="2019-04-06T18:34:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSession -->
      </class> <!-- day10_0406.Express_Action_Item -->
    </test> <!-- Maven_Automation -->
  </suite> <!-- Default Suite -->
</testng-results>
