<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NYCXAXSKASHEW10" name="day10_0406.Express_Action_Item" tests="1" failures="1" timestamp="06 Apr 2019 18:34:00 GMT" time="36.259" errors="0">
  <testcase name="expressCheckout" time="36.259" classname="day10_0406.Express_Action_Item">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Men&#039;s and Women&#039;s Clothing - Shop jeans, dresses, and suits] but found [Mens &amp; Women&#039;s Clothing],
	expected [null] but found [assertion]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Men's and Women's Clothing - Shop jeans, dresses, and suits] but found [Mens & Women's Clothing],
expected [null] but found [assertion]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at day10_0406.Express_Action_Item.expressCheckout(Express_Action_Item.java:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- expressCheckout -->
</testsuite> <!-- day10_0406.Express_Action_Item -->
